name: pointcept
channels:
  - pyg
  - pytorch
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - addict=2.4.0
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blas=1.0
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - cachetools=5.3.3
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cryptography=43.0.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.4
  - einops=0.8.0
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2024.6.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-auth=2.29.0
  - google-auth-oauthlib=0.5.2
  - grpcio=1.62.2
  - h5py=3.11.0
  - hdf5=1.12.1
  - huggingface_hub=0.24.6
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.9.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgrpc=1.62.2
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvpx=1.7.0
  - libwebp-base=1.3.2
  - libxcrypt=4.4.36
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib-base=3.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpld3=0.5.9
  - mpmath=1.3.0
  - multidict=6.0.4
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - ninja-base=1.10.2
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - openblas=0.3.21
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pillow=10.4.0
  - platformdirs=3.10.0
  - plyfile=1.1
  - pooch=1.7.0
  - protobuf=4.25.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=24.2.1
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python_abi=3.8
  - pytorch=2.1.0
  - pytorch-cluster=1.6.3
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.2
  - pytorch-sparse=0.6.18
  - pyyaml=6.0.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rsa=4.7.2
  - safetensors=0.4.5
  - scipy=1.10.1
  - sharedarray=3.2.4
  - six=1.16.0
  - sqlite=3.45.3
  - sympy=1.13.2
  - tbb=2021.8.0
  - tensorboard=2.13.0
  - tensorboard-data-server=0.7.0
  - tensorboardx=2.6.2.2
  - termcolor=2.2.0
  - timm=1.0.11
  - tk=8.6.14
  - tomli=2.0.1
  - torchaudio=2.1.0
  - torchtriton=2.1.0
  - torchvision=0.16.0
  - tqdm=4.66.5
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - werkzeug=3.0.3
  - x264=1!157.20191217
  - xz=5.4.6
  - yaml=0.2.5
  - yapf=0.40.1
  - yarl=1.11.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip=23.1.2
  - pip:
    - asttokens==2.4.1
    - backcall==0.2.0
    - ccimport==0.4.4
    - cloth-simulation-filter==1.1.5
    - comm==0.2.2
    - configargparse==1.7
    - contourpy==1.1.1
    - cumm-cu118==0.4.11
    - cycler==0.12.1
    - cython==3.0.11
    - dash==2.18.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - decorator==5.1.1
    - et-xmlfile==2.0.0
    - executing==2.1.0
    - fastjsonschema==2.20.0
    - fire==0.7.0
    - flask==3.0.3
    - fonttools==4.54.1
    - ipython==8.12.3
    - ipywidgets==8.1.5
    - itsdangerous==2.2.0
    - jedi==0.19.1
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-core==5.7.2
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - lark==1.2.2
    - laspy==2.5.4
    - llvmlite==0.41.1
    - matplotlib==3.7.5
    - matplotlib-inline==0.1.7
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - ninja==1.11.1.1
    - noise==1.2.2
    - numba==0.58.1
    - open3d==0.18.0
    - openpyxl==3.1.5
    - pandas==2.0.3
    - parso==0.8.4
    - patsy==1.0.1
    - pccm==0.4.16
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pip==24.3.1
    - pkgutil-resolve-name==1.3.10
    - plotly==5.24.1
    - portalocker==2.10.1
    - prompt-toolkit==3.0.48
    - psutil==6.1.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pybind11==2.13.6
    - pygments==2.18.0
    - pyparsing==3.1.4
    - pyquaternion==0.9.9
    - pytz==2024.2
    - referencing==0.35.1
    - retrying==1.3.4
    - rpds-py==0.20.0
    - scikit-learn==1.3.2
    - seaborn==0.13.2
    - setuptools==75.3.0
    - spconv-cu118==2.3.6
    - stack-data==0.6.3
    - statsmodels==0.14.1
    - tenacity==9.0.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.5.0
    - torch-geometric==2.6.1
    - traitlets==5.14.3
    - tzdata==2024.2
    - wcwidth==0.2.13
    - wheel==0.45.1
    - widgetsnbextension==4.0.13
    - xlsxwriter==3.2.0
